### ISSUE TITLE
koho.onelink.me

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#10]
Blocking this domain is just a URL shortener to the play store. I do not believe it is malicious.

https://koho.onelink.me/Iw0N/4de1b7bd
redirects to 
https://play.google.com/store/apps/details?id=ca.koho&hl=en_CA&shortlink=4de1b7bd&pid=Website&c=website-google&af_click_lookback=1h

**Comment by DataMaster-2501** [comment]
🙄🙄 You really need to look into/google the domains before you file an issue.
So yes you are right onelink.me is a URL shortener
but a URL shortener for who🤔 oh that's right [AppsFlyer](https://en.wikipedia.org/wiki/AppsFlyer) an Evil mobile marketing analytics company 
So when you go to http://onelink.me/ it's just doing a http 302 redirect to https://www.appsflyer.com/product/one-link-deep-linking/

So now understand why I am blocking that URL shortener

p.s. a lot of time & thought went into making this list.

The domain is not removed
end of line

**Comment by p1r473** [comment]
Thanks for explaining, I was unaware.
