### ISSUE TITLE
www.uptimerobot.com uptimerobot.com

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#15]
www.uptimerobot.com uptimerobot.com 
Not a malicious domain; I believe it may be a false positive
It is a website heartbeat monitor
Thanks!

**Comment by DataMaster-2501** [comment]
I really don't know why this is in my list.
I kind of remember it but don't.
After looking at the website & the API I see no reason to keep in my list
So I will remove all of the subdomains & domain for uptimerobot.com form my list in the next release -> v1.9
