### ISSUE TITLE
False positive: www.ip-tracker.org ip-tracker.org

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#16]
I believe this is a false positive.
These are used for doing research about an IP address. It helps YOU track an IP. It does not track you.

**Comment by DataMaster-2501** [comment]
Sry but no not a false positive.
If you look around the site you will see they offer an API option
https://www.ip-tracker.org/tracer/trace-ip.php
I have seen websites hook into that info
I will recap: my list is not just about ads it is also about privacy.
I make no clam that my list will be right for everyone.
I care about online privacy & I feel we have a right to online privacy.


The domain is not removed
end of line
