### ISSUE TITLE
b-graph.facebook.com

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#18]
Blocking this domain breaks logging into Facebook Messenger on mobile.

**Comment by DataMaster-2501** [comment]
🤔hmm
Does it really break logging into Facebook Messenger on mobile????
grrr damn evil Facebook (I don't use Facebook sry about this)

I'm going to have to look deeper into this.

**Comment by DataMaster-2501** [comment]
I'm going to remove b-graph.facebook.com
