### ISSUE TITLE
kaspersky.com blocked

### ISSUE THREAD

**Issue by mkb2091** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#2]
kaspersky.com and www.kaspersky.com are both blocked, and are actually an anti-virus website

**Comment by DataMaster-2501** [comment]
>  are actually an anti-virus website

No they are an evil company who is controlled by the Russian government & the Russian government are evil dicks....
If you are using kaspersky you should stop using it asap!
When it comes to an anti-virus trust is a big thing & the world can no longer trust kaspersky.
All of kaspersky owned domain names have been added & will not be removed from the list.
https://en.wikipedia.org/wiki/Kaspersky_bans_and_allegations_of_Russian_government_ties

**Comment by mkb2091** [comment]
I wasn't aware of that, thanks for making me aware of my mistake

**Comment by p1r473** [comment]
+1 to remove all the Kaspersky stuff
