### ISSUE TITLE
embed-ssl.wistia.com

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#20]
This false positive breaks embedded videos on any platform hosted by Wistia.
I am experiencing blocks with this domain on stackskills.com which hosts their videos and their thumbnails on Wistia

**Comment by DataMaster-2501** [comment]
And what is on the home page of wistia.com
"Video marketing software that makes it easy to find, engage, and grow your audience"
My list is not just about ads it is also about Privacy & most of all Privacy from the Ad/Marketing industry.

The domain not removed
end of line
