### ISSUE TITLE
false positive edgekey.net

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#21]
edgekey.net is a domain that is owned and used by Akamai that is primarily used for website acceleration through the Akamai CDN. Content Delivery Network (CDN) (About DefBoxes) Content Delivery Networks (CDNs) put website content on servers that are spread throughout the world.

**Comment by DataMaster-2501** [comment]
do try to google & think why I would add that domain as well as other domains

I can remove www.edgekey.net & edgekey.net but all the subdomains in the list stay unless you can show me they are not pushing ads or tracking stuff.

**Comment by p1r473** [comment]
Of note, mi.edgekey.net is a CNAME for miamiherald website, as well as others, so if you block this and people are using deep cname inspection, many sites protected by akamai will by blocked
