### ISSUE TITLE
gab.com

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#23]
**Describe the bug**
Domain blocked

**Expected behavior**
Domain should not be blocked
It contains no ads, spyware, or malware

**Additional context**
This is a social media platform

**Comment by DataMaster-2501** [comment]
it's a site of extreme hate.

**Comment by p1r473** [comment]
It's a free speech social media platform 
Don't believe the main stream media :)

**Comment by edinjapan** [comment]
Looks like this list is engaged in censorship of free speech, instead of just blocking ads
I will cease using this list now
