### ISSUE TITLE
Amazon.ca images wont load

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#3]
Please unblock images-na.ssl-images-amazon.com

**Comment by DataMaster-2501** [comment]
Yeah I have seen this as well.
Normal amazon.com does not do this🙄 but other amazon sites like amazon.ca or amazon.de does.
Today I'm really busy but I will find time tomorrow to remove it as well as push out some updates to the list.
p.s. thank you for taking the time to tell me about this.

**Comment by DataMaster-2501** [comment]
OK I have removed "images-na.ssl-images-amazon.com" & updated the list.
Do let me know if you run into anymore problems with the list.

**Comment by p1r473** [comment]
Thanks!
