### ISSUE TITLE
"delivery.swid.switchadhub.com

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#4]
Invalid domain in blocklist: "delivery.swid.switchadhub.com
It has a " (double quotes)

**Comment by DataMaster-2501** [comment]
oh thank you soo much for pointing this out I will try to push out an update today if I can or tomorrow at the latest.
Again thank you for taking the time to let me know about this.

**Comment by DataMaster-2501** [comment]
This issues has now been fixed in Version 1.6 Release
and thank you for pointing it out to me.
