### ISSUE TITLE
unsubscribe.mailerlite.com

### ISSUE THREAD

**Issue by p1r473** [DataMaster-2501/DataMaster-Android-AdBlock-Hosts#8]
Blocking this domain prevents from unsubscribing from Mailerlite emails

**Comment by DataMaster-2501** [comment]
Yeah be careful when using unsubscribe links in spam/junk e-mails because by clicking the link unsubscribe you are just showing them that some one checks that e-mail so send more e-mails to them.
Yeah I can remove just the sub domain "unsubscribe.mailerlite.com" in release -> v1.9
